In [28]:
import torch

In [29]:
# 1. Создайте случайный FloatTensor размера 3x4x5
t1 = torch.FloatTensor(3, 4, 5)
t1, t1.type()

(tensor([[[4.6120e-36, 0.0000e+00, 2.9287e-43, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
          [1.8788e+31, 1.7220e+22, 2.1715e-18, 3.3275e+21, 3.3587e-06],
          [4.2054e-05, 8.4268e-07, 6.4461e-10, 4.3247e-05, 4.2098e+21]],
 
         [[2.1669e-04, 6.5255e-10, 1.4580e-19, 1.1495e+24, 3.0881e+29],
          [1.5766e-19, 1.8889e+31, 7.2065e+31, 2.8404e+29, 2.3089e-12],
          [1.9421e+31, 2.7491e+20, 6.1949e-04, 1.9421e+31, 2.7491e+20],
          [2.3078e-12, 7.1760e+22, 7.2250e+28, 1.5766e-19, 2.1067e-07]],
 
         [[2.6426e+20, 8.2646e-10, 8.3104e+20, 2.5643e-09, 8.5081e-07],
          [1.3445e+22, 3.4015e+21, 2.3049e-12, 2.6302e+20, 6.1949e-04],
          [6.4805e-10, 2.5203e-09, 1.6992e-04, 6.7977e-04, 6.9368e-07],
          [6.4458e-10, 2.5931e-09, 1.4580e-19, 4.5450e+30, 1.8524e+28]]]),
 'torch.FloatTensor')

In [30]:
# 2. Выведите его форму (shape)
t1.shape

torch.Size([3, 4, 5])

In [31]:
# 3. Приведите его к форме 6х10
t2 = t1.reshape(6, 10)
t2, t2.type()

(tensor([[4.6120e-36, 0.0000e+00, 2.9287e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [1.8788e+31, 1.7220e+22, 2.1715e-18, 3.3275e+21, 3.3587e-06, 4.2054e-05,
          8.4268e-07, 6.4461e-10, 4.3247e-05, 4.2098e+21],
         [2.1669e-04, 6.5255e-10, 1.4580e-19, 1.1495e+24, 3.0881e+29, 1.5766e-19,
          1.8889e+31, 7.2065e+31, 2.8404e+29, 2.3089e-12],
         [1.9421e+31, 2.7491e+20, 6.1949e-04, 1.9421e+31, 2.7491e+20, 2.3078e-12,
          7.1760e+22, 7.2250e+28, 1.5766e-19, 2.1067e-07],
         [2.6426e+20, 8.2646e-10, 8.3104e+20, 2.5643e-09, 8.5081e-07, 1.3445e+22,
          3.4015e+21, 2.3049e-12, 2.6302e+20, 6.1949e-04],
         [6.4805e-10, 2.5203e-09, 1.6992e-04, 6.7977e-04, 6.9368e-07, 6.4458e-10,
          2.5931e-09, 1.4580e-19, 4.5450e+30, 1.8524e+28]]),
 'torch.FloatTensor')

In [32]:
# 4. Создайте случайный IntTensor размера 10
t3 = torch.IntTensor(10)
t3, t3.type()

(tensor([108797952,         0,  16842752,  16843009,  16843009,  16843009,
          16843009,  16843009,  16843009,  16843009], dtype=torch.int32),
 'torch.IntTensor')

In [33]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
xa = t2 * t3
xa

tensor([[5.0177e-28, 0.0000e+00, 4.9328e-36, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [       inf, 0.0000e+00, 3.6574e-11, 5.6045e+28, 5.6570e+01, 7.0832e+02,
         1.4193e+01, 1.0857e-02, 7.2841e+02, 7.0905e+28],
        [2.3576e+04, 0.0000e+00, 2.4557e-12, 1.9362e+31, 5.2013e+36, 2.6555e-12,
         3.1814e+38,        inf, 4.7841e+36, 3.8889e-05],
        [       inf, 0.0000e+00, 1.0434e+04, 3.2712e+38, 4.6303e+27, 3.8870e-05,
         1.2087e+30, 1.2169e+36, 2.6555e-12, 3.5483e+00],
        [2.8751e+28, 0.0000e+00, 1.3997e+28, 4.3191e-02, 1.4330e+01, 2.2645e+29,
         5.7292e+28, 3.8822e-05, 4.4300e+27, 1.0434e+04],
        [7.0506e-02, 0.0000e+00, 2.8620e+03, 1.1449e+04, 1.1684e+01, 1.0857e-02,
         4.3676e-02, 2.4558e-12, 7.6551e+37, 3.1199e+35]])

In [34]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти
xa = xa @ xa.T
xa

tensor([[0.0000e+00,        inf,        nan,        inf, 1.4427e+01, 3.5392e-29],
        [       inf,        inf,        inf,        inf,        inf,        inf],
        [       nan,        inf,        inf,        inf,        inf,        inf],
        [       inf,        inf,        inf,        inf,        inf,        inf],
        [1.4427e+01,        inf,        inf,        inf,        inf,        inf],
        [3.5392e-29,        inf,        inf,        inf,        inf,        inf]])

In [35]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor([1.], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.], requires_grad=True)

y = x**3 + z - 75*t

y.backward()

print('dy/dx: ', x.grad)
print('dy/dz: ', z.grad)
print('dy/dt: ', t.grad)

dy/dx:  tensor([3.])
dy/dz:  tensor([1.])
dy/dt:  tensor([-75.])


In [36]:
# 8. Создайте единичный тензор размера 5x6
# 8. Создайте единичный тензор размера 5x6

t_ones = torch.ones(5, 6)
t_ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [37]:
# 9. Переведите его в формат numpy
# 8. Создайте единичный тензор размера 5x6

t_ones = t_ones.numpy()
t_ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)